model_name: mobilenetv3_small
img_size: 224
batch_size: 64
epochs: 30
dataset:
  path: ../../data/citrus_5_classes
  val_split: 0.2
  class_names: [Greening, Canker, Melanose, Black_Spot, Healthy]
save_dir: ../../weights/mobilenetv3_small
